### ISSUE TITLE
case-3-js-html/index.js : UnhandledPromiseRejectionWarning: ReferenceError: Y is not defined

### ISSUE THREAD

**Issue by mejustdev** [pbeshai/beshai-makes-code#4]
There is a conflict between index.js and raw format of it. 
In index.js line 85, there is a `and` variable which is not declared. But also in the raw file it has been parsed to capital -- `Y` variable which is not intended. It should be `y`. 
I fixed the issue easily change capital `Y` to `y` but it is interesting to see this. Maybe it is related with Github?

`Index.js`

![index](https://user-images.githubusercontent.com/48910851/115985049-4bd1dc00-a5aa-11eb-9fa1-deee6d0c39f3.png)

`Raw index.js`

![raw](https://user-images.githubusercontent.com/48910851/115985057-54c2ad80-a5aa-11eb-8f3d-fb57dd3beb1a.png)

**Comment by pbeshai** [comment]
I'm not seeing that on my end. Maybe you've got a browser extension that is somehow messing with it? Could try cloning or downloading the repo and checking there, but it doesn't appear for me.
